.PONY: build run

CC=gcc
C_OUT=server
C_SRC=*.c
C_FLAGS=-ljson-c 

build:
	@$(CC) -o $(C_OUT) $(C_SRC) $(C_FLAGS)

run:
	@./$(C_OUT)

clean:
	@rm $(C_OUT)

	# gcc server.c requestHandler.c requestHandler.h -ljson-c -o server